INSERT OR IGNORE INTO store_items (id, name, description, type, category, price_coins, rarity, item_data) VALUES
('bg-void','Void','O cosmos padrão. As estrelas do começo.','background','starfield',0,'free','{"type":"starfield","color1":"rgba(255,255,255,0.35)","color2":"rgba(255,255,255,0.55)","color3":"rgba(255,255,255,0.85)","density":1.0,"speed":1.0}'),
('bg-neon-cyan','Neon Cyan','Cyan elétrico. Para quem faz do grind um estilo de vida.','background','starfield',800,'common','{"type":"starfield","color1":"rgba(34,211,238,0.28)","color2":"rgba(34,211,238,0.52)","color3":"rgba(34,211,238,0.90)","density":1.0,"speed":1.0}'),
('bg-crimson','Crimson','Vermelho intenso. Para os que não têm medo de falhar.','background','starfield',1500,'common','{"type":"starfield","color1":"rgba(239,68,68,0.28)","color2":"rgba(239,68,68,0.50)","color3":"rgba(239,68,68,0.88)","density":1.0,"speed":1.0}'),
('bg-amber','Amber Glow','Ouro queimado. Conquista visível.','background','starfield',1500,'common','{"type":"starfield","color1":"rgba(234,179,8,0.28)","color2":"rgba(234,179,8,0.52)","color3":"rgba(234,179,8,0.88)","density":1.0,"speed":1.2}'),
('bg-deep-purple','Deep Purple','Roxo profundo. Raridade visível.','background','starfield',2000,'rare','{"type":"starfield","color1":"rgba(168,85,247,0.28)","color2":"rgba(168,85,247,0.52)","color3":"rgba(168,85,247,0.90)","density":1.2,"speed":0.9}'),
('bg-void-dense','Void Dense','O void, mais denso. Mais estrelas para os persistentes.','background','starfield',2500,'rare','{"type":"starfield","color1":"rgba(255,255,255,0.28)","color2":"rgba(255,255,255,0.50)","color3":"rgba(255,255,255,0.85)","density":2.5,"speed":0.8}'),
('bg-matrix','Matrix','Verde. Rápido. Só para quem chegou aqui de propósito.','background','starfield',3000,'rare','{"type":"starfield","color1":"rgba(34,197,94,0.28)","color2":"rgba(34,197,94,0.52)","color3":"rgba(34,197,94,0.90)","density":1.5,"speed":2.2}'),
('bg-gold-rush','Gold Rush','Lendário. Não se compra fácil — nem com dinheiro.','background','starfield',5000,'legendary','{"type":"starfield","color1":"rgba(251,191,36,0.32)","color2":"rgba(251,191,36,0.58)","color3":"rgba(251,191,36,0.95)","density":2.0,"speed":1.3}'),
('mat-green','Matrix Green','Chars caindo em verde terminal. Clássico.','background','matrix',0,'free','{"type":"matrix","color1":"#00ff41","color2":"#007722","color3":"#002211"}'),
('mat-cyan','Matrix Cyan','O terminal, mas em azul elétrico.','background','matrix',0,'free','{"type":"matrix","color1":"#22d3ee","color2":"#0891b2","color3":"#0e4a5e"}'),
('mat-red','Matrix Red','Código caindo em vermelho. Urgência permanente.','background','matrix',0,'free','{"type":"matrix","color1":"#ef4444","color2":"#991b1b","color3":"#450a0a"}'),
('mat-rainbow','Matrix Rainbow','Chars em gradiente arco-íris. Caótico e bonito.','background','matrix',0,'free','{"type":"matrix","color1":"#ff0050","color2":"#00ff88","color3":"#0080ff"}'),
('mat-fire','Matrix Fire','Código em chamas. Do branco ao vermelho.','background','matrix',0,'free','{"type":"matrix","color1":"#ffffff","color2":"#ff6600","color3":"#cc2200"}'),
('mat-ice','Matrix Ice','Chars congelados. Do branco ao roxo profundo.','background','matrix',0,'free','{"type":"matrix","color1":"#ffffff","color2":"#0088ff","color3":"#6600cc"}'),
('rain-cyan','Rain Cyan','Chuva em cyan. Atmosférico e sereno.','background','rain',0,'free','{"type":"rain","color1":"#09f"}'),
('rain-green','Rain Green','Chuva verde. Natureza binária.','background','rain',0,'free','{"type":"rain","color1":"#0f0"}'),
('rain-purple','Rain Purple','Chuva roxa. Misteriosa.','background','rain',0,'free','{"type":"rain","color1":"#a855f7"}'),
('rain-neon','Rain Neon','Chuva em rosa neon com hue-rotate. Sintética.','background','rain',0,'free','{"type":"rain","color1":"#ff00cc"}'),
('rain-fire','Rain Fire','Chuva alaranjada. Quente.','background','rain',0,'free','{"type":"rain","color1":"#ff6600"}'),
('rain-teal','Rain Teal','Chuva em verde-azulado. Fresca.','background','rain',0,'free','{"type":"rain","color1":"#00d4aa"}'),
('aurora-default','Aurora','Borealis em roxo, cyan e verde. O clássico.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(138,43,226,0.8)","color2":"rgba(0,191,255,0.7)","color3":"rgba(50,205,50,0.6)"}'),
('aurora-fire','Aurora Fire','Borealis em tons de fogo. Vermelho ao amarelo.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(239,68,68,0.8)","color2":"rgba(249,115,22,0.7)","color3":"rgba(234,179,8,0.6)"}'),
('aurora-ocean','Aurora Ocean','Borealis em azul profundo e verde oceano.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(59,130,246,0.8)","color2":"rgba(20,184,166,0.7)","color3":"rgba(34,197,94,0.6)"}'),
('aurora-synthwave','Aurora Synthwave','Borealis em roxo, rosa e azul. Anos 80.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(168,85,247,0.8)","color2":"rgba(236,72,153,0.7)","color3":"rgba(59,130,246,0.6)"}'),
('aurora-nature','Aurora Nature','Borealis em tons de verde e esmeralda.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(34,197,94,0.8)","color2":"rgba(20,184,166,0.7)","color3":"rgba(163,230,53,0.6)"}'),
('aurora-dusk','Aurora Dusk','Borealis em coral, laranja e magenta. Pôr do sol.','background','aurora',0,'free','{"type":"aurora","color1":"rgba(251,113,133,0.8)","color2":"rgba(249,115,22,0.7)","color3":"rgba(236,72,153,0.6)"}'),
('sky-white','Midnight White','Estrelas brancas e lua crescente. O clássico.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#ffffff"}'),
('sky-blue','Midnight Blue','Estrelas em azul frio. Noite ártica.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#60a5fa"}'),
('sky-amber','Midnight Amber','Estrelas douradas. Noite quente do deserto.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#fbbf24"}'),
('sky-neon','Midnight Neon','Estrelas em cyan elétrico. Cidade à noite.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#22d3ee"}'),
('sky-purple','Midnight Purple','Estrelas roxas. Noite mágica.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#a78bfa"}'),
('sky-crimson','Midnight Crimson','Estrelas vermelhas. Noite de batalha.','background','midnight-sky',0,'free','{"type":"midnight-sky","color1":"#f87171"}'),
('radial-default','Radial Burst','Explosão radial com hue-rotate. RGB completo.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#f00","color2":"#ff0","color3":"#0f0"}'),
('radial-cool','Radial Cool','Explosão em azul, cyan e violeta.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#00f","color2":"#0ff","color3":"#a0f"}'),
('radial-warm','Radial Warm','Explosão em vermelho, laranja e amarelo.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#f00","color2":"#f80","color3":"#ff0"}'),
('radial-acid','Radial Acid','Explosão em verde ácido e limão.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#0f0","color2":"#cf0","color3":"#ff0"}'),
('radial-neon','Radial Neon','Explosão em magenta, cyan e lima. Puro neon.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#f0f","color2":"#0ff","color3":"#cf0"}'),
('radial-deep','Radial Deep','Explosão em roxo profundo e índigo.','background','radial-burst',0,'free','{"type":"radial-burst","color1":"#320085","color2":"#6600cc","color3":"#4400aa"}'),
('neon-grid-default','Neon Grid','Grid de pontos neon em rosa, cyan e azul.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#ff00cc","color2":"#00ffcc","color3":"#3300ff"}'),
('neon-grid-fire','Neon Grid Fire','Grid em vermelho, laranja e amarelo.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#ff2200","color2":"#ff8800","color3":"#ffee00"}'),
('neon-grid-ocean','Neon Grid Ocean','Grid em azul, teal e violeta.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#0066ff","color2":"#00ccaa","color3":"#6600ff"}'),
('neon-grid-matrix','Neon Grid Matrix','Grid em verde puro. Terminal em grade.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#00ff44","color2":"#44ff00","color3":"#00cc22"}'),
('neon-grid-sunset','Neon Grid Sunset','Grid em laranja, rosa e violeta. Pôr do sol sintético.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#ff6600","color2":"#ff0080","color3":"#8800ff"}'),
('neon-grid-ice','Neon Grid Ice','Grid em cyan, branco e azul. Frio total.','background','neon-grid',0,'free','{"type":"neon-grid","color1":"#00ffff","color2":"#aaddff","color3":"#0088ff"}');
